### ISSUE TITLE
speed up na.interpolation

### ISSUE THREAD

**Issue by SpotSeven** [SteffenMoritz/imputeTS#7]
linear and spline interpolation can probably be made faster performance wise
(slightly different interpolation implementations from zoo package seem to be a little bit quicker)

**Comment by SteffenMoritz** [comment]
Will be fixed with 1.8 version.
na.interpolation will be up to 10000 times faster now.

Inspiration on how to speed up was actually taken from zoo package. So thx to the creators of this package. Did some additional improvements so the current 1.8 imputeTS na.locf function is also about 10 times faster than the na.locf function of zoo.
